* Как примонтировать раздел с veracrypt на OpenBSD

Кратко: В два этапа.
Сначала примонтировать раздел как виртуальный диск на файле.
То есть с pseudo-device vnd(4).

Затем, примонтировать файловую систему с этого виртуального диска на файле.
В данном случае это может быть FAT32, exfat, ntfs-3g


** veracrypt --mount

Монтируем зашифрованный диск, без указания файловой системы.

#+begin_src shell
doas  veracrypt --text --mount /dev/sd2i --password=my_simple_pass --filesystem=none --verbose
#+end_src

Если veracrypt сам не распознает данные вначале раздела, то он вам об этом сообщит и статус завершения команды будет не равен нулю.
Однако это актуально для случая без стеганографии, про который пока ничего добавить не могу.

Если команда выполнилась успешно, то смотрим список примонтированных veracrypt разделов.

#+begin_src shell
doas veracrypt --text --list --verbose
#+end_src

Таким образом будут перечисленны примонтированные разделы.
В моём упрощенном случае тут только один раздел и он примонтирован как файл виртуального диска.
Местоположение файла смотрим в строке начинающейся со словосочетания =Virtual Device=

#+begin_src shell
doas veracrypt --text --list --verbose | grep "Virtual Device"
#+end_src 

** mount virtual device

В моём случае, внутри зашифрованного раздела veracrypt находиться раздел с файловой системой ntfs.

Монтирую её с помощью ntfs-3g из портов.
Указываю uid своего пользователя, чтобы дальше не повышать привелегии при доступе к файлам на файловой системе.
Если вам файловой системы хватит и в режиме чтения только, то можно использовать mount_ntfs из базы.

#+begin_src shell
doas ntfs-3g -o uid=1000 /dev/vnd0c /mnt/disk
#+end_src
