** Виртуальная частная сеть

У большинства людей неправильное представление для чего изначально нужен vpn.
VPN нужен не просто для обхода блокировок, как обычный прокси сервер,
но может ещё использоваться и для объеденения в одну,
как бы локальную, сеть нескольких физически удалённых компьютеров.
На то она и *виртуальная частная* сеть.
 

Возможно, некоторые знают, а некоторые нет, но я пишу
курсовой по системам баз данных, так вот я настроил vpn
в том числе для того, чтобы удобно подключиться к базе данных
на удалённом сервере.

Теперь могу просто:

#+BEGIN_SRC: shell
wg-quick up private.conf
psql -h 172.16.1.1 -p 5432 -U postgres
#+END_SRC

Как вы, наверное знаете 172.16.1.1 это ip-адресс выделенный
под private internets и в глобальном интернете не маршрутизируется.

Но это только с домашнего вайфая,
с eduroam обрывает соединение и  приходится использовать ssh-туннель:
https://www.postgresql.org/docs/current/ssh-tunnels.html


**** Тэги.
Они теперь будут выглядет так потому что я использую [[https://howm.osdn.jp/][howm].

<<< vpn
<<< wireguard
<<< databases
<<< bsuir
